name: bidirectional_scroll
description: A highly customizable, feature rich Scroll widget for Flutter.
version: 2.0.1
repository: https://github.com/tejainece/bidirectional_scroll

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
